version: 2
jobs:
  build:
    docker:
      - image: docker:latest
    steps:
      - checkout

      - setup_remote_docker:
          docker_layer_caching: true
          
      - run: |
          TAG=latest
          docker build -t $DOCKER_USER/gcloud-fluxctl:$TAG .
          echo "$DOCKER_PASS" | docker login -u "$DOCKER_USERNAME" --password-stdin
          docker push $DOCKER_USER/gcloud-fluxctl:$TAG .
